# Tarrex's kitty config
# https://sw.kovidgoyal.net/kitty/conf

# Fonts
font_family      family="JetBrains Mono" variable_name=JetBrainsMono style=Regular
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 20.0

# modify_font cell_width 80%
# modify_font cell_height -2px
# modify_font baseline 3

# Cursor
cursor_shape beam
cursor_beam_thickness 2
cursor_blink_interval -1
cursor_stop_blinking_after 15.0

# Scrollback
scrollback_lines 100000
scrollbar scrolled-and-hovered

# Mouse
open_url_with default
copy_on_select yes

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Bell
enable_audio_bell no
visual_bell_duration 0.0

# Window layout
remember_window_size  yes
initial_window_width  1200
initial_window_height 800

enabled_layouts splits,stack

window_border_width 0.5pt

window_padding_width 10

placement_strategy center

hide_window_decorations titlebar-only

confirm_os_window_close 0

# Tab bar
tab_bar_edge top
tab_bar_style separator
tab_separator " ⎥"
tab_bar_align left
tab_title_template "{index}: {title}"
active_tab_font_style bold

# Color scheme
background_opacity 0.80
background_blur 20
dynamic_background_opacity yes

# include themes/Gruvbox_Dark_Hard.conf
include themes/Solarized_Dark_Higher_Contrast.conf
# include themes/PaperColor_Dark.conf
# include themes/Solarized_Dark_Patched.conf

# Advanced
term xterm-kitty

# OS specific tweaks
macos_quit_when_last_window_closed yes
macos_traditional_fullscreen yes
macos_show_window_title_in menubar

# Keyboard shortcuts
kitty_mod ctrl+shift

## Clipboard
map cmd+c copy_or_noop
map cmd+v paste_from_clipboard

## Scrolling
map cmd+up      scroll_line_up
map cmd+down    scroll_line_down
map cmd+f       search_scrollback

## Window management
map cmd+enter   discard_event
map cmd+n       new_os_window_with_cwd
map cmd+shift+d close_os_window

## Tab management
map cmd+t new_tab_with_cwd
map cmd+w close_tab
map cmd+[ previous_tab
map cmd+] next_tab

## Layout management
map ctrl+shift+v launch --location=vsplit --cwd=current
map ctrl+shift+h launch --location=hsplit --cwd=current

## Font sizes
map cmd+equal       change_font_size all +2.0
map cmd+shift+minus change_font_size all -2.0
map cmd+0           change_font_size all 0

## Select and act on visible text
map ctrl+shift+p>l kitten hints --type line --program -
map ctrl+shift+p>w kitten hints --type word --program -

## Miscellaneous
map ctrl+cmd+f  toggle_fullscreen

map cmd+`       macos_cycle_through_os_windows
map cmd+shift+` macos_cycle_through_os_windows_backwards

map cmd+,       edit_config_file
map ctrl+cmd+,  load_config_file
map opt+cmd+,   debug_config

map ctrl+shift+a>m set_background_opacity +0.1
map ctrl+shift+a>l set_background_opacity -0.1
map ctrl+shift+a>1 set_background_opacity 1
map ctrl+shift+a>d set_background_opacity default

map cmd+l clear_terminal scroll active

map cmd+h       hide_macos_app
map opt+cmd+h   hide_macos_other_apps
map cmd+m       minimize_macos_window
map cmd+q       quit

map cmd+alt+left  neighboring_window left
map cmd+alt+right neighboring_window right
map cmd+alt+up    neighboring_window up
map cmd+alt+down  neighboring_window down
