# Tarrex's kitty config
# https://sw.kovidgoyal.net/kitty/conf

# Fonts
font_family      family='JetBrains Mono' variable_name=JetBrainsMono style=Regular
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 20.0

disable_ligatures always

# Cursor
cursor_shape beam
cursor_beam_thickness 2

# Scrollback
scrollback_lines 10000
scrollback_pager_history_size 10
scrollbar scrolled-and-hovered

# Mouse
copy_on_select clipboard

# Bell
enable_audio_bell no

# Window layout
remember_window_size  yes
remember_window_position yes
initial_window_width  1200
initial_window_height 800

enabled_layouts splits,stack
window_border_width 0.5pt
window_padding_width 6
single_window_padding_width 10
hide_window_decorations titlebar-only
confirm_os_window_close -1

# Tab bar
tab_bar_edge top
tab_bar_style separator
tab_separator ' │ '
tab_bar_align left
tab_title_max_length 24
tab_title_template '{index}: {secure_input_symbol}{title}'
active_tab_font_style bold

# Color scheme
background_opacity 0.80
background_blur 20
dynamic_background_opacity yes

# include themes/Gruvbox_Dark_Hard.conf
include themes/Solarized_Dark_Higher_Contrast.conf
# include themes/PaperColor_Dark.conf
# include themes/Solarized_Dark_Patched.conf
# include themes/Tokyo_Night.conf
# include themes/Modus_Vivendi_Tinted.conf

# OS specific tweaks
macos_quit_when_last_window_closed yes
macos_traditional_fullscreen yes
macos_show_window_title_in menubar
macos_menubar_title_max_length 40

# Shortcuts
map cmd+l       clear_terminal scroll active
map cmd+enter   toggle_fullscreen
map ctrl+cmd+p  command_palette

map ctrl+cmd+t  new_tab_with_cwd
map ctrl+cmd+n  new_os_window_with_cwd

map cmd+d       launch --location=split  --cwd=current
map ctrl+cmd+v  launch --location=vsplit --cwd=current
map ctrl+cmd+h  launch --location=hsplit --cwd=current

map ctrl+cmd+r  layout_action rotate
map ctrl+cmd+e  layout_action equalize

map cmd+opt+left    neighboring_window left
map cmd+opt+right   neighboring_window right
map cmd+opt+up      neighboring_window up
map cmd+opt+down    neighboring_window down
